version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mixoads_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mixoads
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mock-api:
    build:
      context: ./mock-api
    container_name: mixoads_mock_api
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
